version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    expose: 
      - "27017"

  api_v2:
    build: 
      context: .
      dockerfile: Dockerfile.V2
    ports:
      - "8081:8081"
    environment: 
      FORECAST_URL: ${FORECAST_URL}
      MONGO_URI: ${MONGO_URI}
    depends_on: 
      - mongodb

  api_v1:
    build: 
      context: .
      dockerfile: Dockerfile.V1
    ports:
      - "8080:8080"
    environment: 
      FORECAST_URL: ${FORECAST_URL}
      MONGO_URI: ${MONGO_URI_DOCKER}
    depends_on: 
      - mongodb